
/*
This Java source file was generated by test-to-java.xsl
and is a derived work from the source document.
The source document contained the following notice:


Copyright (c) 2001 World Wide Web Consortium,
(Massachusetts Institute of Technology, Institut National de
Recherche en Informatique et en Automatique, Keio University). All
Rights Reserved. This program is distributed under the W3C's Software
Intellectual Property License. This program is distributed in the
hope that it will be useful, but WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
See W3C License http://www.w3.org/Consortium/Legal/ for more details.

*/

package org.w3c.domts.level1.core;

import org.w3c.dom.*;

import org.w3c.domts.*;
import javax.xml.parsers.*;
import java.util.*;



/**
* 
    The "createCDATASection(data)" method creates a new 
   CDATASection node whose value is the specified string.
   Retrieve the entire DOM document and invoke its 
   "createCDATASection(data)" method.  It should create a
   new CDATASection node whose "data" is the specified 
   string.  The content, name and type are retrieved and
   output.

* @author NIST
* @author Mary Brady
* @see <a href="http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-D26C0AF8">http://www.w3.org/TR/1998/REC-DOM-Level-1-19981001/level-one-core#ID-D26C0AF8</a>
*/
public class documentcreatecdatasection extends DOMTestCase {

   public documentcreatecdatasection(DOMTestDocumentBuilderFactory factory)  {
      super(factory);
   }

   public void runTest() throws java.lang.Throwable {
      Document doc;
      CDATASection newCDATASectionNode;
      String newCDATASectionValue;
      String newCDATASectionName;
      int newCDATASectionType;
      doc = load("staff");
      newCDATASectionNode = doc.createCDATASection("This is a new CDATASection node");
      newCDATASectionValue = newCDATASectionNode.getNodeValue();
      assertEquals("nodeValue","This is a new CDATASection node",newCDATASectionValue);
      newCDATASectionName = newCDATASectionNode.getNodeName();
      assertEquals("nodeName","#cdata-section",newCDATASectionName);
      newCDATASectionType = (int)newCDATASectionNode.getNodeType();
      assertEquals("nodeType",4,newCDATASectionType);
      
   }
   public String getTargetURI() {
      return "http://www.w3.org/2001/DOM-Test-Suite/level1/core/documentcreatecdatasection";
   }
   public static void main(String[] args) {
        DOMTestCase.doMain(documentcreatecdatasection.class,args);
   }
}
